import React from 'react';

interface SafeHighlightProps {
  text: string;
  className?: string;
}

export const SafeHighlight: React.FC<SafeHighlightProps> = ({ text, className = '' }) => {
  if (!text) return null;

  // Split on <b> and </b> tags generated by FTS snippet
  // Tokenize safely into text nodes without executing any embedded HTML or JavaScript
  const tokens = text.split(/(<\/?b>)/gi);
  let isBold = false;

  return (
    <span className={className}>
      {tokens.map((token, idx) => {
        if (token.toLowerCase() === '<b>') {
          isBold = true;
          return null;
        }
        if (token.toLowerCase() === '</b>') {
          isBold = false;
          return null;
        }

        // Render plain text node (React automatically HTML-escapes all string children)
        if (isBold) {
          return (
            <strong
              key={idx}
              className="text-sky-300 font-semibold bg-sky-950/80 px-1 py-0.2 rounded border border-sky-800/40"
            >
              {token}
            </strong>
          );
        }

        return <React.Fragment key={idx}>{token}</React.Fragment>;
      })}
    </span>
  );
};
